#!/usr/bin/env bash

BASEDIR=$(dirname "$0")

echo -e "\n\nInstalling Ukiyo...\n\n"
xcode-select -p 1>/dev/null

if [ $? -ne 0 ]; then
  xcode-select --install
fi

if ! [ -x "$(command -v brew)" ]; then
  /usr/bin/ruby -e "$(curl -fsSL \
    https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew install pyenv
yes n | pyenv install 3.9.1
pyenv global 3.9.1
brew install mackup
cp ./backup/.mackup.cfg ~/.mackup.cfg
mackup -f restore
brew bundle --file=~/Brewfile
eval "$(pyenv init -)"
echo Using $(python --version)
# pip3 install powerline-status --user
# chmod u+x ~/.local/lib/python3.9/site-packages/powerline/bindings/shell/powerline.sh
cp $BASEDIR/fonts/SFMono-Light-Nerd.otf ~/Library/Fonts
sudo cp $BASEDIR/backup/Library/Preferences/com.googlecode.iterm2.plist ~/com.googlecode.iterm2.plist
source ~/.zprofile

echo -e "\n\n\x1b[37m"
figlet -f $BASEDIR/fonts/Calvin\ S.flf UKIYO
echo -e "\x1b[37m☳ \x1b[36mdev//environment\n\n\n\x1b[37m"
